name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    
    container:
      image: node:20
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up node 20 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build with Maven
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-dependencies: true
      - run: |
            cd frontend
            cd src
            python3 -m http.server 8000 &
            sleep 10 &&
            curl http://localhost:8000
            cd ..
            cd tests
            npm install
            ./node_modules/.bin/mocha *.js
            cd ..
            cd backend/calculator_back
             mvn clean spring-boot:run & 
             echo "waiting 5 seconds for the server to start"
             sleep 5 
             attempt_counter=0
             max_attempts=5
             until $(curl --output /dev/null --silent --head --fail http://localhost:8080/add); do
                if [ ${attempt_counter} -eq ${max_attempts} ];then
                  echo "Max attempts reached"
                  exit 1
                fi
            
                printf '.'
                attempt_counter=$(($attempt_counter+1))
                sleep 5
             done
             echo "sever ready for testing"
             npm install -g newman
             newman -v
             newman run src/test/java/com/example/calculator_back/integration/calculator.postman_collection.json
            
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
          
